import type {
  BusinessResult,
  User,
  ExtractionFilter,
  SavedSearch,
  BillingPlan,
  Invoice,
} from "./types"

export const PRICE_PER_1000 = 10 // $10 per 1,000 results
export const PRICE_PER_RESULT = PRICE_PER_1000 / 1000 // $0.01 per result

export function estimateCost(count: number): string {
  return `$${(count * PRICE_PER_RESULT).toFixed(2)}`
}

export const mockUser: User = {
  id: "usr_1",
  name: "Arjun Mehta",
  email: "arjun@example.com",
  avatar: undefined,
  credits: 8640,
}

export const mockResults: BusinessResult[] = [
  {
    id: "biz_1",
    title: "Joe's Pizza",
    subtitle: "New York Style Pizza",
    categoryName: "Pizza restaurant",
    categories: ["Pizza restaurant", "Italian restaurant", "Delivery restaurant"],
    address: "7 Carmine St, New York, NY 10014",
    neighborhood: "Greenwich Village",
    street: "7 Carmine St",
    city: "New York",
    postalCode: "10014",
    state: "New York",
    countryCode: "US",
    phone: "+1 212-366-1182",
    website: "http://www.joespizzanyc.com",
    url: "https://www.google.com/maps/place/?q=place_id:ChIJxWLy8DlZwokR1cX_wjEMTIw",
    totalScore: 4.5,
    reviewsCount: 12847,
    reviewsDistribution: { oneStar: 412, twoStar: 308, threeStar: 721, fourStar: 2841, fiveStar: 8565 },
    imageUrl: "https://lh5.googleusercontent.com/p/AF1QipN",
    location: { lat: 40.7302, lng: -74.0024 },
    placeId: "ChIJxWLy8DlZwokR1cX_wjEMTIw",
    cid: "9876543210123456789",
    permanentlyClosed: false,
    temporarilyClosed: false,
    openingHours: [
      { day: "Monday", hours: "10:00 AM - 4:00 AM" },
      { day: "Tuesday", hours: "10:00 AM - 4:00 AM" },
      { day: "Wednesday", hours: "10:00 AM - 4:00 AM" },
      { day: "Thursday", hours: "10:00 AM - 4:00 AM" },
      { day: "Friday", hours: "10:00 AM - 5:00 AM" },
      { day: "Saturday", hours: "10:00 AM - 5:00 AM" },
      { day: "Sunday", hours: "10:00 AM - 4:00 AM" },
    ],
    plusCode: "Q234+XP New York",
    price: "$",
    menu: "http://www.joespizzanyc.com/menu",
    description: "Quintessential New York pizza joint serving classic thin-crust slices since 1975.",
    additionalInfo: { "Service options": ["Dine-in", "Takeout", "Delivery"], Payments: ["Credit cards", "NFC mobile payments"] },
    reservationLinks: [],
    orderLinks: ["https://order.joespizzanyc.com"],
    emails: ["info@joespizzanyc.com"],
    socialMedia: [{ platform: "Instagram", url: "https://instagram.com/joespizzanyc" }],
    claimStatus: "Claimed",
    isAdvertisement: false,
    leadScore: "hot",
  },
  {
    id: "biz_2",
    title: "Tatiana by Kwame Onwuachi",
    subtitle: "Contemporary American Fine Dining",
    categoryName: "American restaurant",
    categories: ["American restaurant", "Fine dining restaurant", "Bar"],
    address: "10 Lincoln Center Plaza, New York, NY 10023",
    neighborhood: "Lincoln Square",
    street: "10 Lincoln Center Plaza",
    city: "New York",
    postalCode: "10023",
    state: "New York",
    countryCode: "US",
    phone: "+1 212-871-8764",
    website: "https://www.tatiananyc.com",
    url: "https://www.google.com/maps/place/?q=place_id:ChIJrxNRX7BYwokRNLjbzgMH5Gg",
    totalScore: 4.7,
    reviewsCount: 2341,
    reviewsDistribution: { oneStar: 38, twoStar: 47, threeStar: 134, fourStar: 512, fiveStar: 1610 },
    imageUrl: null,
    location: { lat: 40.7725, lng: -73.9835 },
    placeId: "ChIJrxNRX7BYwokRNLjbzgMH5Gg",
    cid: "1234567890123456789",
    permanentlyClosed: false,
    temporarilyClosed: false,
    openingHours: [
      { day: "Monday", hours: "Closed" },
      { day: "Tuesday", hours: "5:00 PM - 10:00 PM" },
      { day: "Wednesday", hours: "5:00 PM - 10:00 PM" },
      { day: "Thursday", hours: "5:00 PM - 10:00 PM" },
      { day: "Friday", hours: "5:00 PM - 11:00 PM" },
      { day: "Saturday", hours: "11:00 AM - 11:00 PM" },
      { day: "Sunday", hours: "11:00 AM - 9:00 PM" },
    ],
    plusCode: "Q2X4+7P New York",
    price: "$$$$",
    menu: "https://www.tatiananyc.com/menus",
    description: "Celebrity chef Kwame Onwuachi's acclaimed restaurant at Lincoln Center featuring Afro-Caribbean-American cuisine.",
    additionalInfo: { "Service options": ["Dine-in", "Outdoor seating"], Payments: ["Credit cards"] },
    reservationLinks: ["https://resy.com/cities/ny/tatiana"],
    orderLinks: [],
    emails: ["reservations@tatiananyc.com"],
    socialMedia: [{ platform: "Instagram", url: "https://instagram.com/tatabornyc" }],
    claimStatus: "Claimed",
    isAdvertisement: false,
    leadScore: "warm",
  },
  {
    id: "biz_3",
    title: "Katz's Delicatessen",
    subtitle: "Iconic Jewish Deli",
    categoryName: "Delicatessen",
    categories: ["Delicatessen", "Restaurant", "Sandwich shop"],
    address: "205 E Houston St, New York, NY 10002",
    neighborhood: "Lower East Side",
    street: "205 E Houston St",
    city: "New York",
    postalCode: "10002",
    state: "New York",
    countryCode: "US",
    phone: "+1 212-254-2246",
    website: "https://www.katzsdelicatessen.com",
    url: "https://www.google.com/maps/place/?q=place_id:ChIJA3CBoSlZwokRu0-AMk_uBME",
    totalScore: 4.6,
    reviewsCount: 28402,
    reviewsDistribution: { oneStar: 1136, twoStar: 568, threeStar: 1420, fourStar: 5680, fiveStar: 19598 },
    imageUrl: null,
    location: { lat: 40.7223, lng: -73.9874 },
    placeId: "ChIJA3CBoSlZwokRu0-AMk_uBME",
    cid: "2345678901234567890",
    permanentlyClosed: false,
    temporarilyClosed: false,
    openingHours: [
      { day: "Monday", hours: "8:00 AM - 10:45 PM" },
      { day: "Tuesday", hours: "8:00 AM - 10:45 PM" },
      { day: "Wednesday", hours: "8:00 AM - 10:45 PM" },
      { day: "Thursday", hours: "8:00 AM - 2:45 AM" },
      { day: "Friday", hours: "8:00 AM - 2:45 AM" },
      { day: "Saturday", hours: "8:00 AM - 2:45 AM" },
      { day: "Sunday", hours: "8:00 AM - 10:45 PM" },
    ],
    plusCode: "P2XG+MH New York",
    price: "$$",
    menu: "https://www.katzsdelicatessen.com/menu",
    description: "Since 1888, an iconic NYC institution famous for hand-carved pastrami and corned beef sandwiches.",
    additionalInfo: { "Service options": ["Dine-in", "Takeout", "Delivery"], Accessibility: ["Wheelchair accessible entrance"] },
    reservationLinks: [],
    orderLinks: ["https://order.katzsdelicatessen.com"],
    emails: ["info@katzsdelicatessen.com", "catering@katzsdelicatessen.com"],
    socialMedia: [{ platform: "Instagram", url: "https://instagram.com/katzsdelicatessen" }, { platform: "Facebook", url: "https://facebook.com/katzsdelicatessen" }],
    claimStatus: "Claimed",
    isAdvertisement: false,
    leadScore: "hot",
  },
  {
    id: "biz_4",
    title: "Le Bernardin",
    subtitle: "French Seafood Fine Dining",
    categoryName: "French restaurant",
    categories: ["French restaurant", "Seafood restaurant", "Fine dining restaurant"],
    address: "155 W 51st St, New York, NY 10019",
    neighborhood: "Midtown Manhattan",
    street: "155 W 51st St",
    city: "New York",
    postalCode: "10019",
    state: "New York",
    countryCode: "US",
    phone: "+1 212-554-1515",
    website: "https://www.le-bernardin.com",
    url: "https://www.google.com/maps/place/?q=place_id:ChIJV4gWp7VYwokRfbS_r76VjOY",
    totalScore: 4.7,
    reviewsCount: 6823,
    reviewsDistribution: { oneStar: 102, twoStar: 68, threeStar: 273, fourStar: 1365, fiveStar: 5015 },
    imageUrl: null,
    location: { lat: 40.7616, lng: -73.9817 },
    placeId: "ChIJV4gWp7VYwokRfbS_r76VjOY",
    cid: "3456789012345678901",
    permanentlyClosed: false,
    temporarilyClosed: false,
    openingHours: [
      { day: "Monday", hours: "12:00 PM - 10:30 PM" },
      { day: "Tuesday", hours: "12:00 PM - 10:30 PM" },
      { day: "Wednesday", hours: "12:00 PM - 10:30 PM" },
      { day: "Thursday", hours: "12:00 PM - 10:30 PM" },
      { day: "Friday", hours: "12:00 PM - 11:00 PM" },
      { day: "Saturday", hours: "5:15 PM - 11:00 PM" },
      { day: "Sunday", hours: "Closed" },
    ],
    plusCode: "Q2GC+FJ New York",
    price: "$$$$",
    menu: "https://www.le-bernardin.com/menus",
    description: "Michelin three-star seafood restaurant led by Chef Eric Ripert, one of NYC's most celebrated dining experiences.",
    additionalInfo: { "Service options": ["Dine-in"], "Dining options": ["Dessert"], Payments: ["Credit cards", "NFC mobile payments"] },
    reservationLinks: ["https://www.opentable.com/le-bernardin"],
    orderLinks: [],
    emails: ["info@le-bernardin.com"],
    socialMedia: [{ platform: "Instagram", url: "https://instagram.com/lebernardinny" }],
    claimStatus: "Claimed",
    isAdvertisement: false,
    leadScore: "warm",
  },
  {
    id: "biz_5",
    title: "Halal Guys",
    subtitle: "Halal Street Food",
    categoryName: "Middle Eastern restaurant",
    categories: ["Middle Eastern restaurant", "Halal restaurant", "Fast food restaurant"],
    address: "W 53rd St & 6th Ave, New York, NY 10019",
    neighborhood: "Midtown Manhattan",
    street: "W 53rd St & 6th Ave",
    city: "New York",
    postalCode: "10019",
    state: "New York",
    countryCode: "US",
    phone: null,
    website: "https://thehalalguys.com",
    url: "https://www.google.com/maps/place/?q=place_id:ChIJEWN-P71YwokR5yPXCkKlVbQ",
    totalScore: 4.3,
    reviewsCount: 18234,
    reviewsDistribution: { oneStar: 1459, twoStar: 729, threeStar: 1823, fourStar: 3647, fiveStar: 10576 },
    imageUrl: null,
    location: { lat: 40.7614, lng: -73.9794 },
    placeId: "ChIJEWN-P71YwokR5yPXCkKlVbQ",
    cid: "4567890123456789012",
    permanentlyClosed: false,
    temporarilyClosed: false,
    openingHours: [
      { day: "Monday", hours: "10:00 AM - 4:00 AM" },
      { day: "Tuesday", hours: "10:00 AM - 4:00 AM" },
      { day: "Wednesday", hours: "10:00 AM - 4:00 AM" },
      { day: "Thursday", hours: "10:00 AM - 4:00 AM" },
      { day: "Friday", hours: "10:00 AM - 4:00 AM" },
      { day: "Saturday", hours: "10:00 AM - 4:00 AM" },
      { day: "Sunday", hours: "10:00 AM - 4:00 AM" },
    ],
    plusCode: "Q2GC+CQ New York",
    price: "$",
    menu: null,
    description: "World-famous street cart turned chain known for platters of gyro meat, chicken, and signature white and red sauces.",
    additionalInfo: { "Service options": ["Takeout", "No-contact delivery"] },
    reservationLinks: [],
    orderLinks: ["https://order.thehalalguys.com"],
    emails: [],
    socialMedia: [{ platform: "Facebook", url: "https://facebook.com/TheHalalGuys" }],
    claimStatus: "Claimed",
    isAdvertisement: false,
    leadScore: "warm",
  },
  {
    id: "biz_6",
    title: "Peter Luger Steak House",
    subtitle: "Legendary Brooklyn Steakhouse",
    categoryName: "Steak house",
    categories: ["Steak house", "American restaurant", "Bar & grill"],
    address: "178 Broadway, Brooklyn, NY 11211",
    neighborhood: "Williamsburg",
    street: "178 Broadway",
    city: "Brooklyn",
    postalCode: "11211",
    state: "New York",
    countryCode: "US",
    phone: "+1 718-387-7400",
    website: "https://peterluger.com",
    url: "https://www.google.com/maps/place/?q=place_id:ChIJtUx6LmxbwokRJ-hELqHsnLc",
    totalScore: 4.4,
    reviewsCount: 9176,
    reviewsDistribution: { oneStar: 550, twoStar: 275, threeStar: 642, fourStar: 1835, fiveStar: 5874 },
    imageUrl: null,
    location: { lat: 40.7099, lng: -73.9624 },
    placeId: "ChIJtUx6LmxbwokRJ-hELqHsnLc",
    cid: "5678901234567890123",
    permanentlyClosed: false,
    temporarilyClosed: false,
    openingHours: [
      { day: "Monday", hours: "11:45 AM - 9:45 PM" },
      { day: "Tuesday", hours: "11:45 AM - 9:45 PM" },
      { day: "Wednesday", hours: "11:45 AM - 9:45 PM" },
      { day: "Thursday", hours: "11:45 AM - 9:45 PM" },
      { day: "Friday", hours: "11:45 AM - 10:45 PM" },
      { day: "Saturday", hours: "11:45 AM - 10:45 PM" },
      { day: "Sunday", hours: "12:45 PM - 9:45 PM" },
    ],
    plusCode: "P2VV+GH Brooklyn",
    price: "$$$$",
    menu: "https://peterluger.com/menu",
    description: "Cash-only German beer hall-style steakhouse est. 1887, famous for porterhouse steaks and creamed spinach.",
    additionalInfo: { "Service options": ["Dine-in", "Takeout"], Payments: ["Cash only", "Peter Luger card"] },
    reservationLinks: ["https://www.peterluger.com/reservations"],
    orderLinks: [],
    emails: ["info@peterluger.com"],
    socialMedia: [],
    claimStatus: "Claimed",
    isAdvertisement: false,
    leadScore: "hot",
  },
  {
    id: "biz_7",
    title: "Los Tacos No. 1",
    subtitle: "Authentic Mexican Tacos",
    categoryName: "Mexican restaurant",
    categories: ["Mexican restaurant", "Taco restaurant"],
    address: "75 9th Ave, New York, NY 10011",
    neighborhood: "Chelsea",
    street: "75 9th Ave",
    city: "New York",
    postalCode: "10011",
    state: "New York",
    countryCode: "US",
    phone: "+1 212-256-0343",
    website: "https://lostacos1.com",
    url: "https://www.google.com/maps/place/?q=place_id:ChIJb4QV4L1ZwokRwJR3mGbINkw",
    totalScore: 4.6,
    reviewsCount: 7583,
    reviewsDistribution: { oneStar: 152, twoStar: 152, threeStar: 379, fourStar: 1517, fiveStar: 5383 },
    imageUrl: null,
    location: { lat: 40.7425, lng: -74.0060 },
    placeId: "ChIJb4QV4L1ZwokRwJR3mGbINkw",
    cid: "6789012345678901234",
    permanentlyClosed: false,
    temporarilyClosed: false,
    openingHours: [
      { day: "Monday", hours: "11:00 AM - 9:00 PM" },
      { day: "Tuesday", hours: "11:00 AM - 9:00 PM" },
      { day: "Wednesday", hours: "11:00 AM - 9:00 PM" },
      { day: "Thursday", hours: "11:00 AM - 9:00 PM" },
      { day: "Friday", hours: "11:00 AM - 10:00 PM" },
      { day: "Saturday", hours: "11:00 AM - 10:00 PM" },
      { day: "Sunday", hours: "11:00 AM - 9:00 PM" },
    ],
    plusCode: "P2W5+3X New York",
    price: "$",
    menu: "https://lostacos1.com/menu",
    description: "Popular Chelsea Market taqueria serving handmade tortillas with carne asada, adobada, and nopal fillings.",
    additionalInfo: { "Service options": ["Dine-in", "Takeout"] },
    reservationLinks: [],
    orderLinks: [],
    emails: ["hello@lostacos1.com"],
    socialMedia: [{ platform: "Instagram", url: "https://instagram.com/lostacos1" }],
    claimStatus: "Claimed",
    isAdvertisement: false,
    leadScore: "warm",
  },
  {
    id: "biz_8",
    title: "Russ & Daughters Cafe",
    subtitle: "Jewish Appetizing & Cafe",
    categoryName: "Cafe",
    categories: ["Cafe", "Jewish restaurant", "Brunch restaurant"],
    address: "127 Orchard St, New York, NY 10002",
    neighborhood: "Lower East Side",
    street: "127 Orchard St",
    city: "New York",
    postalCode: "10002",
    state: "New York",
    countryCode: "US",
    phone: "+1 212-475-4880",
    website: "https://www.russanddaughters.com",
    url: "https://www.google.com/maps/place/?q=place_id:ChIJcbhAzBNZwokRZBsdFzg5uMk",
    totalScore: 4.5,
    reviewsCount: 4892,
    reviewsDistribution: { oneStar: 147, twoStar: 98, threeStar: 245, fourStar: 978, fiveStar: 3424 },
    imageUrl: null,
    location: { lat: 40.7207, lng: -73.9888 },
    placeId: "ChIJcbhAzBNZwokRZBsdFzg5uMk",
    cid: "7890123456789012345",
    permanentlyClosed: false,
    temporarilyClosed: false,
    openingHours: [
      { day: "Monday", hours: "9:00 AM - 10:00 PM" },
      { day: "Tuesday", hours: "9:00 AM - 10:00 PM" },
      { day: "Wednesday", hours: "9:00 AM - 10:00 PM" },
      { day: "Thursday", hours: "9:00 AM - 10:00 PM" },
      { day: "Friday", hours: "9:00 AM - 10:00 PM" },
      { day: "Saturday", hours: "8:00 AM - 10:00 PM" },
      { day: "Sunday", hours: "8:00 AM - 10:00 PM" },
    ],
    plusCode: "P2XF+GM New York",
    price: "$$",
    menu: "https://www.russanddaughters.com/cafe-menu",
    description: "Sit-down extension of the legendary 1914 appetizing shop, known for smoked fish, bagels, and egg creams.",
    additionalInfo: { "Service options": ["Dine-in", "Takeout"], Accessibility: ["Wheelchair accessible entrance"] },
    reservationLinks: ["https://resy.com/cities/ny/russ-and-daughters-cafe"],
    orderLinks: [],
    emails: ["cafe@russanddaughters.com"],
    socialMedia: [{ platform: "Instagram", url: "https://instagram.com/russanddaughters" }],
    claimStatus: "Claimed",
    isAdvertisement: false,
    leadScore: "cold",
  },
]

export const mockFilter: ExtractionFilter = {
  searchQuery: "Restaurants",
  locationQuery: "New York, USA",
  maxResults: 100,
  language: "en",
  region: "us",
  skipClosedPlaces: true,
  scrapeEmails: true,
  scrapeSocialMedia: true,
  scrapeReviewsDetail: false,
  maxReviews: 0,
  estimatedCredits: 100,
  costEstimate: "$1.00",
}

export const mockSavedSearches: SavedSearch[] = [
  {
    id: "ss-1",
    name: "NYC Restaurants 4+ Stars",
    query: "Find top 500 restaurants in New York with 4+ star rating",
    filters: { ...mockFilter, maxResults: 500, estimatedCredits: 500, costEstimate: "$5.00" },
    resultsCount: 487,
    creditsUsed: 487,
    costAmount: 4.87,
    createdAt: new Date("2026-02-10T14:30:00"),
    status: "completed",
  },
  {
    id: "ss-2",
    name: "SF Coffee Shops",
    query: "Coffee shops in San Francisco, open now",
    filters: { ...mockFilter, searchQuery: "coffee shops", locationQuery: "San Francisco, CA", maxResults: 200, estimatedCredits: 200, costEstimate: "$2.00" },
    resultsCount: 183,
    creditsUsed: 183,
    costAmount: 1.83,
    createdAt: new Date("2026-02-08T09:15:00"),
    status: "completed",
  },
  {
    id: "ss-3",
    name: "Chicago Dentists High Rating",
    query: "Dentists in Chicago with 4.5+ stars and 200+ reviews",
    filters: { ...mockFilter, searchQuery: "dentists", locationQuery: "Chicago, IL", maxResults: 1000, scrapeReviewsDetail: true, maxReviews: 10, estimatedCredits: 1000, costEstimate: "$10.00" },
    resultsCount: 742,
    creditsUsed: 742,
    costAmount: 7.42,
    createdAt: new Date("2026-02-05T16:45:00"),
    status: "completed",
  },
  {
    id: "ss-4",
    name: "LA Auto Repair Shops",
    query: "Auto repair shops in Los Angeles with 100+ reviews",
    filters: { ...mockFilter, searchQuery: "auto repair", locationQuery: "Los Angeles, CA", maxResults: 300, estimatedCredits: 300, costEstimate: "$3.00" },
    resultsCount: 289,
    creditsUsed: 289,
    costAmount: 2.89,
    createdAt: new Date("2026-02-01T11:20:00"),
    status: "completed",
  },
  {
    id: "ss-5",
    name: "Miami Hotels Premium",
    query: "Hotels in Miami Beach with 4+ stars",
    filters: { ...mockFilter, searchQuery: "hotels", locationQuery: "Miami Beach, FL", maxResults: 150, estimatedCredits: 150, costEstimate: "$1.50" },
    resultsCount: 134,
    creditsUsed: 134,
    costAmount: 1.34,
    createdAt: new Date("2026-01-28T08:45:00"),
    status: "completed",
  },
]

export const billingPlans: BillingPlan[] = [
  {
    id: "starter",
    name: "Starter",
    price: 0,
    resultsPerMonth: 250,
    pricePerResult: "Free",
    features: [
      "250 results/month",
      "CSV & JSON export",
      "30+ data fields per result",
      "Email scraping included",
      "Community support",
    ],
  },
  {
    id: "growth",
    name: "Growth",
    price: 49,
    resultsPerMonth: 5000,
    pricePerResult: "$0.0098/result",
    features: [
      "5,000 results/month",
      "All export formats (CSV, Excel, JSON)",
      "Email + Social media scraping",
      "Review detail scraping",
      "2 CRM connectors (HubSpot, Zoho)",
      "Saved searches",
      "Priority support",
    ],
    popular: true,
  },
  {
    id: "business",
    name: "Business",
    price: 149,
    resultsPerMonth: 20000,
    pricePerResult: "$0.0075/result",
    features: [
      "20,000 results/month",
      "All export formats",
      "Full data enrichment (30+ fields)",
      "All 5 CRM connectors",
      "Review detail scraping (up to 50/place)",
      "Dedicated support",
      "API access",
      "Custom field mapping",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 399,
    resultsPerMonth: 100000,
    pricePerResult: "$0.004/result",
    features: [
      "100,000 results/month",
      "White-label exports",
      "Custom CRM integrations",
      "Bulk extraction queue",
      "SLA guarantee (99.9%)",
      "Dedicated account manager",
      "Custom billing & invoicing",
      "Webhook notifications",
    ],
  },
]

export const mockInvoices: Invoice[] = [
  {
    id: "INV-2026-004",
    date: new Date("2026-02-01"),
    amount: 49.00,
    resultsUsed: 6420,
    status: "paid",
    description: "Growth Plan - February 2026",
  },
  {
    id: "INV-2026-003",
    date: new Date("2026-01-01"),
    amount: 49.00,
    resultsUsed: 8937,
    status: "paid",
    description: "Growth Plan - January 2026",
  },
  {
    id: "INV-2025-002",
    date: new Date("2025-12-01"),
    amount: 49.00,
    resultsUsed: 7214,
    status: "paid",
    description: "Growth Plan - December 2025",
  },
  {
    id: "INV-2025-001",
    date: new Date("2025-11-01"),
    amount: 49.00,
    resultsUsed: 9102,
    status: "paid",
    description: "Growth Plan - November 2025",
  },
]
